site_name: VoiceScriptPlayer Docs
site_description: Documentation for VoiceScriptPlayer
site_url: https://VoiceScriptPlayer.github.io/vsp-docs/

theme:
  name: material
  language: ko
  custom_dir: overrides          # ğŸ‘ˆ overrides í´ë” ì¶”ê°€
  features:
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - search.highlight
  icon:
    repo: fontawesome/brands/patreon


nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Project:
      - ìƒˆ í”„ë¡œì íŠ¸ ë§Œë“¤ê¸°: project/create.md
      - ë¶ˆëŸ¬ì˜¤ê¸° & ì €ì¥: project/manage.md
  - Editor:
      - ê°œìš”: editor/overview.md
      - íƒ€ì„ë¼ì¸: editor/timeline.md
      - ì‚¬ìš´ë“œ: editor/sound.md
      - ë¹„ë””ì˜¤: editor/video.md
      - Live2D: editor/live2d.md
      - UI: editor/ui.md
      - ìŠ¤í¬ë¦½íŠ¸: editor/script.md
      - ìŠ¤íŠ¸ë¡œí¬: editor/stroke.md
      - ì‚¬ì • ì•¡ì…˜: editor/ejaculation.md
      - ë¦¬ì†ŒìŠ¤ ê´€ë¦¬: editor/resources.md
      - ëŸ°íƒ€ì„ ë„ìš°ë¯¸: editor/runtime-helper.md
  - Playback:
      - ì‹¤í–‰í•˜ê¸°: playback/run.md
      - ë””ë²„ê·¸ & ë¡œê·¸: playback/debug.md
  - Features: features.md
  - Device:
      - TCode: device/tcode.md
      - Intiface: device/intiface.md
  - AI:
      - SpeechRecognition: ai/speechRecognition.md
      - Whisper: ai/whisper.md
      - ElevenLabs: ai/elevenlabs.md
      - COEIROINK: ai/coeiroink.md
      - Hailuo: ai/hailuo.md
      - LibreTranslate: ai/libretranslate.md
      - DeepL: ai/deepl.md
  - FAQ: faq.md

plugins:
  - search
  - i18n:
      languages:
        - locale: ko
          name: í•œêµ­ì–´
          default: true      # â† ê¸°ë³¸ ì–¸ì–´
          build: true        # â† ì´ ì–¸ì–´ë¡œ ë¹Œë“œí•¨
        - locale: en
          name: English
          build: true
        - locale: ja
          name: æ—¥æœ¬èª
          build: true
      nav_translations:
        en:
          Home: Home
          Getting Started: Getting Started
          Project: Project
          Editor: Editor
          Playback: Playback
          Features: Features
          Device: Device
          AI: AI
          FAQ: FAQ
        ja:
          Home: ãƒ›ãƒ¼ãƒ 
          Getting Started: ã¯ã˜ã‚ã«
          Project: ãƒ—ãƒ­ã‚¸ã‚§ã‚¯ãƒˆ
          Editor: ã‚¨ãƒ‡ã‚£ã‚¿ãƒ¼
          Playback: å†ç”Ÿ
          Features: æ©Ÿèƒ½
          Device: ãƒ‡ãƒã‚¤ã‚¹
          AI: AI
          FAQ: ã‚ˆãã‚ã‚‹è³ªå•


markdown_extensions:
  - admonition
  - def_list
  - tables
  - toc:
      permalink: true

extra:
  nav:
    - icon: fontawesome/brands/patreon
      link: https://www.patreon.com/VoiceScriptPlayer
      name: Patreon
  alternate:
    - name: í•œêµ­ì–´
      link: /
      lang: ko
    - name: English
      link: /en/
      lang: en
    - name: æ—¥æœ¬èª
      link: /ja/
      lang: ja
  social:
    - icon: fontawesome/brands/patreon
      link: https://www.patreon.com/VoiceScriptPlayer
      name: Patreon